server:
  port: 8082
  servlet:
    context-path: /product
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/virspit_product
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    show-sql: true
