spring:
  profiles:
    active: local

  application.name: virspit-product
  data.web.pageable:
    max-page-size: 100
    one-indexed-parameters: true
  servlet.multipart:
    max-file-size: 10MB
    max-request-size: 10MB