server:
  port: 8081

---
#eureka:
#
#  instance:
#    instance-id: product-microservice-instance
#
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka

---

spring:
  datasource:
    url: jdbc:mariadb://virspit-product.crtppt0lvgk7.ap-northeast-2.rds.amazonaws.com:3306/virspit_product
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    show-sql: true
    properties.hibernate.format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  data.web.pageable.max-page-size: 100

  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      bootstrap-servers: 15.164.129.26:9092
      group-id: product_group
      auto-offset-reset: earliest

    producer:
      bootstrap-servers: 15.164.129.26:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

kafka:
  topic:
    product: product
    order: order

kas:
  chainId: 1001
  fee-payer:
    krn: krn:1001:wallet:1e96a061-f2bb-40ec-bb68-456e125cf20d:feepayer-pool:fee-payer
    address: "0xf57392DEC64F0EC7859F11284eF23Db23b111d35"

file.dir: /tmp/