version: "3"
services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - ./data/db:/data/db
    container_name: "mongodb"
    ports:
      - 27017:27017
    command: --smallfiles
  virspit-listing:
    image: song22an/virspit-listing:latest
    ports:
      - 8081:8080
    links:
      - mongodb
    volumes:
      - ./config/listing.yml:/myapp/application.yml