version: "3"
services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - ./data/db:/data/db
    container_name: "mongodb2"
    ports:
      - 27018:27017
    command: --smallfiles

  virspit-listing:
    image: song22an/virspit-listing:latest
    container_name: virspit-listing
    ports:
      - 8081:8080
    volumes:
      - ./config/listing.yml:/myapp/application.yml