
server:
  port: 8070
---
eureka:
  instance:
    instance-id: gateway-instance
    prefer-ip-address: true

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://3.38.44.130:8761/eureka

---
spring:

  application:
    name: virspit-gateway

  cloud:
    gateway:
      routes:
        - id: virspit-user
          uri: lb://VIRSPIT-USER
          predicates:
            - Path=/member/**
          filters:
            - JwtUserRequestFilter

        - id: virspit-auth
          uri: lb://VIRSPIT-AUTH
          predicates:
            - Path=/auth/**

        - id: virspit-product
            uri: lb://VIRSPIT-PRODUCT
            predicates:
              - Path=/product/**
            filters:
              - JwtUserRequestFilter

        - id: virspit-order
          uri: lb://VIRSPIT-ORDER
          predicates:
            - Path=/order/**

jwt:
  secret: temp