
server:
  port: 8080
---

#eureka:
#  instance:
#    hostname: localhost
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#    service-url:
#      defaultZone: https://${eureka.instance.hostname}:${server.port}/eureka/

---

#spring:
#  cloud:
#    gateway:
#      default-filters:
#        - name:
#          args:
#            baseMessage: Spring Cloud Gateway GlobalFilter
#            preLogger: true
#            postLogger: true
#      routes:
#        - id: user-svc
#          uri: http://localhost:8083/
#          predicates:
#            - Path=/auth/**
#          filters:
#            - name: UserFilter
#              args:
#                baseMessage: Spring Cloud Gateway UserFilter
#                preLogger: true
#                postLogger: true
#        - id: admin-svc
#          uri: http://localhost:8082/
#          predicates:
#            - Path=/admin/**
#          filters:
#            - name: AdminFilter
#              args:
#                baseMessage: Spring Cloud Gateway AdminFilter
#                preLogger: true
#                postLogger: true

jwt:
  secret: temp