
server:
  port: 8080
---
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

---
spring:

  application:
    name: virspit-gateway

  cloud:
    gateway:
      routes:
        - id: virspit-user
          uri: lb://VIRSPIT-USER
          predicates:
            - Path=/user/**
          filters:
            - JwtRequestFilter

        - id: virspit-auth
          uri: lb://VIRSPIT-AUTH
          predicates:
            - Path=/auth/**
            -
        - id: virspit-order
            uri: lb://VIRSPIT-ORDER
            predicates:
              - Path=/order/**

jwt:
  secret: temp