server:
  port: 8070
---
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:

  application:
    name: virspit-gateway

  cloud:
    gateway:
      default-filters:
        - name: DefaultFilter # 글로벌 설정
          args:
            baseMessage: Virspit Spring Cloud Gateway
            preLogger: true
            postLogger: true

      routes:
        - id: virspit-user
          uri: lb://VIRSPIT-USER
          predicates:
            - Path=/member/**
          filters:
            - JwtUserRequestFilter

        - id: virspit-auth
          uri: lb://VIRSPIT-AUTH
          predicates:
            - Path=/auth/**


        - id: virspit-order-user
          uri: lb://VIRSPIT-ORDER
          predicates:
            - Path=/ord2ers/**,/orders/**
            - Method=POST
          filters:
            - JwtUserRequestFilter

        - id: virspit-order-user2
          uri: lb://VIRSPIT-ORDER
          predicates:
            - Path=/orders/**
          filters:

      httpclient:
        wiretap: true
jwt:
  secret: temp


logging:
  level:
    org.springframework.cloud.gateway: trace
