server:
  port: 8070
---
eureka:
  instance:
    instance-id: gateway-instance
    prefer-ip-address: true
    non-secure-port: ${server.port}

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://3.37.16.78:8761/eureka

---
spring:

  application:
    name: virspit-gateway

  cloud:
    gateway:
      routes:


        - id: virspit-user
          uri: lb://VIRSPIT-USER
          predicates:
            - Path=/member/**,/favorite/**,/wallet/**
          filters:
            - JwtUserRequestFilter

        - id: virspit-auth
          uri: lb://VIRSPIT-AUTH
          predicates:
            - Path=/auth/**

        - id: virspit-listing-user
          uri: lb://VIRSPIT-LISTING
          predicates:
            - Path=/products/list/**,/advertisements/**
            - Method=GET
          filters:

        - id: virspit-listing-admin
          uri: lb://VIRSPIT-LISTING
          predicates:
            - Path=/advertises/**,/advertisements/**
          filters:
            - JwtAdminRequestFilter





        - id: virspit-product-user
          uri: lb://VIRSPIT-PRODUCT
          predicates:
            - Path=/sports/**,/team-players/**,/products/**
            - Method=GET


        - id: virspit-product-admin
          uri: lb://VIRSPIT-PRODUCT
          predicates:
            - Path=/sports/**,/team-players/**,/products/**
          filters:
            - JwtAdminRequestFilter



        - id: virspit-order-user
          uri: lb://VIRSPIT-ORDER
          predicates:
            - Path=/orders
            - Method=Post
          filters:
            - JwtUserRequestFilter

        - id: virspit-order-user2
          uri: lb://VIRSPIT-ORDER
          predicates:
            - Path=/orders/members/**
          filters:
            - JwtUserRequestFilter

        - id: virspit-order-admin
          uri: lb://VIRSPIT-ORDER
          predicates:
            - Path=/orders/**
          filters:
            - JwtAdminRequestFilter



jwt:
  secret: temp