server:
  port: 8070
---
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:

  application:
    name: virspit-gateway

  cloud:
    gateway:
      routes:


        - id: virspit-user
          uri: lb://VIRSPIT-USER
          predicates:
            - Path=/member/**
          filters:
            - JwtUserRequestFilter

        - id: virspit-auth
          uri: lb://VIRSPIT-AUTH
          predicates:
            - Path=/auth/**


        - id: virspit-listing-user
          uri: lb://VIRSPIT-PRODUCT
          predicates:
            - Path=/products/list/**,/advertisements/**
            - Method=GET
          filters:
            - JwtUserRequestFilter

        - id: virspit-listing-admin
          uri: lb://VIRSPIT-PRODUCT
          predicates:
            - Path=/advertises/**,/advertisements/**
          filters:
            - JwtAdminRequestFilter


        - id: virspit-product-user
          uri: lb://VIRSPIT-PRODUCT
          predicates:
            - Path=/sports/**,/team-playes/**,/products/**
            - Method=GET
          filters:
            - JwtUserRequestFilter

        - id: virspit-product-admin
          uri: lb://VIRSPIT-PRODUCT
          predicates:
            - Path=/sports/**,/team-playes/**,/products/**
            - Method=GET
          filters:
            - JwtAdminRequestFilter

        - id: virspit-order-user
          uri: lb://VIRSPIT-ORDER
          predicates:
            - Path=/orders
            - Method=Post
          filters:
            - JwtUserRequestFilter

        - id: virspit-order-user2
          uri: lb://VIRSPIT-ORDER
          predicates:
            - Path=/orders/members/**
          filters:
            - JwtUserRequestFilter

        - id: virspit-order-admin
          uri: lb://VIRSPIT-ORDER
          predicates:
            - Path=/orders/**
          filters:
            - JwtAdminRequestFilter


jwt:
  secret: temp