
server:
  port: 8080
---
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

---
spring:

  application:
    name: virspit-gateway

  cloud:
    gateway:
      routes:
        - id: virspit-user
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
          filters:
            - JwtRequestFilter

        - id: virspit-admin
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**

jwt:
  secret: temp