
server:
  port: 8070
---
eureka:
  instance:
    instance-id: gateway-instance
    prefer-ip-address: true
    non-secure-port: ${server.port}

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://3.38.44.130:8761/eureka

---
spring:

  application:
    name: virspit-gateway

  cloud:
    gateway:
      routes:


        - id: virspit-user
          uri: lb://VIRSPIT-USER
          predicates:
            - Path=/member/**,/favorite/**,/wallet/**
          filters:
            - JwtUserRequestFilter

        - id: virspit-auth
          uri: lb://VIRSPIT-AUTH
          predicates:
            - Path=/auth/**

        - id: virspit-product-user
          uri: lb://VIRSPIT-PRODUCT
          predicates:
            - Path=/sports/**,/team-playes/**,/products/**

      httpclient:
        wiretap: true


logging:
  level:
    org.springframework.cloud.gateway: trace



jwt:
  secret: temp