server:
  port: 8083
  servlet:
    context-path: /auth

---

eureka:

  instance:
    instance-id: auth-microservice-instance

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://3.38.44.130:8761/eureka


feign:
  httpclient:
    connection-timeout: 160000000

---

spring:
  application:
    name: virspit-auth

  redis:
    port: 6379
    host: 3.38.44.130

  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true



logging:
  level:
    org.hibernate:
      SQL: DEBUG # to logger
      type.descriptor.sql.BasicBinder: TRACE
    org.springframework.jdbc.core:
      JdbcTemplate: DEBUG
      StatementCreatorUtils: TRACE

---
jwt:
  secret: temp

---
my:
  ip: 3.38.44.130

---
